### ISSUE TITLE
Support MSSQL >= 2005

### ISSUE THREAD

**Issue by EdZava** [sqlectron/sqlectron-core#2]
Plan Support MSSQL >= 2005 ??

Because not used as motor Waterline ?
https://github.com/balderdashy/waterline

**Comment by maxcnunes** [comment]
Hi,

Unfortunately, any of the current contributors use MSSQL. So I guess we will not implement it. But I would glad accept any pull request including this support. 

In case you are interested sending a pull request. Basically you would need to duplicate any file from [/src/db/clients](https://github.com/sqlectron/sqlectron-core/tree/master/src/db/clients) including support for MSSQL. And to ensure all the public APIs are working as expected also include the MSSQL client in the tests [spec/db.spec.js](https://github.com/sqlectron/sqlectron-core/blob/master/spec/db.spec.js#L9).

I didn't know this waterline module. But anyway I think we would not use it because its a ORM, so has much more than we need. Actually we tried to use [knex](http://knexjs.org/). But because the way the connections pool are implemented we had problems handling connections through SSH connections.

**Comment by luisrudge** [comment]
@maxcnunes How are you planning to test sql server? I want to do this, but I'm not sure how we'll add tests for a db. http://www.appveyor.com/ has sql server, so maybe we can test there? If that's the case, we should add this project to appveyor first, then add sql server support.

What do you think?

**Comment by maxcnunes** [comment]
@luisrudge I was planing to use the travis ci. But just found out there is no support for MSSQL server yet. But they have plan to add support for Windows and MSSQL in the future. So what we could do is, configure MySQL and PostgreSQL on travis and MSSQL on appveyor. Once travis has support for MSSQL we can check again if is worth migrating it to travis.

I created the project on appveyor. What is your email then I can add you as a collaborator (if you prefer you can send it by PM on twitter - maxcnunes).

**Comment by luisrudge** [comment]
luis at luisrudge.net

**Comment by maxcnunes** [comment]
Done. Let me know if you need anything else.

**Comment by luisrudge** [comment]
Almost there..
![image](https://cloud.githubusercontent.com/assets/941075/11666098/e5de1872-9dd1-11e5-834d-93461cecbb45.png)

@maxcnunes if you host a Sql Server in Azure, you can't list databases. Should we just return [] if the db is hosted in Azure? Or an error? What do you think?

**Comment by maxcnunes** [comment]
I have removed the assert of default tables from the tests ([here](https://github.com/sqlectron/sqlectron-core/commit/f3417df29ab27f4c424391b917b4844ff38f2fc6)). That is the reason the tests on Docker were breaking after you changes. You used the root user in the AppVeyor tests and I was using a "common" user in the Docker tests. This way I think for now we can just ignore the default tables in the tests.

**Comment by luisrudge** [comment]
Awesome! I'll replicate that. I have only 1 test failing :D

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/11671519/2ff70f68-9df0-11e5-835c-5627a240670d.png)

:astonished:

**Comment by maxcnunes** [comment]
:clap:

**Comment by AdrianoCahete** [comment]
:heart_eyes:

**Comment by AdrianoCahete** [comment]
It's necessary to update readme.

**Comment by krolow** [comment]
thx @AdrianoCahete i've updated, once we get into gui and term we release the sql server, by updating website and other readme, for now we have updated core :)
