### ISSUE TITLE
Support for Sqlite

### ISSUE THREAD

**Issue by arkhan** [sqlectron/sqlectron-core#26]
Hello, great work,

It's posible to add Support to SQLite data bases

Thanks

**Comment by BornaP** [comment]
It is, should be quite easy actually. After finding right Node module for SQLite, rest of the work is implementing API which should be very similar to SQL Server implementation I guess. So more or less copy and rewrite :)

I don't have time for this right now, so if you want feel free to contribute! Pull request is welcome! 

(Else, if it remains unresolved I'll implement this when I catch some more time.)

**Comment by AngeloR** [comment]
Would this module be ok as a base? https://www.npmjs.com/package/sqlite

**Comment by maxcnunes** [comment]
Maybe is better use the original package https://github.com/mapbox/node-sqlite3

**Comment by AngeloR** [comment]
The reason I opted for the sqlite module instead of the sqlite3 module was more to ensure a standard programming style. Yes it is an additional layer of dependency, but using the wrapper ensures that the client can take advantage of es6 and be written in a similar manner as the rest of the clients. I felt that it would make maintaining the codebase easier.

**Comment by maxcnunes** [comment]
Yeah makes sense. But most of the DB clients we use today are using callback instead of Promise. And we wrap them with Promise inside the `sqlectron-core`:

* mysql - [callback](https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/mysql.js#L198)
* postgres - [callback](https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/postgresql.js#L218)
* sqlserver - [promise](https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/sqlserver.js#L69)

My only concern of using the original package is maintainability and have full support of the available functions. In case the API of the original package change or they fix something, we do not depend on this other package to get the latest version.

**Comment by AngeloR** [comment]
Ok, I'll use the original sqlite3 package instead for this PR.

**Comment by thisispiers** [comment]
+1

There aren't any great cross-platform SQLite GUIs. I'd really appreciate the feature so I've posted [a bounty](https://www.bountysource.com/issues/35150328-support-for-sqlite) of $15.

**Comment by maxcnunes** [comment]
@thisispiers thanks for the incentive :)

**Comment by maxcnunes** [comment]
Anyone interested in this feature. Please tests your queries (simple and complex) [here](http://maxcnunes.com/sql-query-identifier/) and let me know if there is any bug. We need to use that because the sqlite module does not have a single function that is able to return results and return the inserted/affected rows at same time. With this package we are able to break down the queries and distinguish its type so we know what function use for each query.

**Comment by maxcnunes** [comment]
Finished.
Commit https://github.com/sqlectron/sqlectron-core/commit/770b06c605e66dcef86fc4c6aed2f6e12a8ca408

**Comment by thisispiers** [comment]
Wow! Thanks Max.

**Comment by BornaP** [comment]
Good job Max!!!
