### ISSUE TITLE
Return full command object

### ISSUE THREAD

**Issue by kwent** [sqlectron/sqlectron-core#44]
### Return full command object

My app was relying on `executionType` attribute from the `command` object returned by https://github.com/maxcnunes/sql-query-identifier but starting `7.4.0`, `sqlectron-core` is just returning `type` attribute for all clients. Cause this modification: https://github.com/sqlectron/sqlectron-core/commit/770b06c605e66dcef86fc4c6aed2f6e12a8ca408#diff-2f30d89cc6b8682e2400496f14c263e2R265. Why this breaking behavior ?

I try to hack around and reverse the `.map((item) => item.type);`. Everything works as i expect again except for `sqlite` client who works a bit differently and return just the `type`. I would love to have the full object with `executionType` as well to be consistent with all other clients.

Regards

**Comment by maxcnunes** [comment]
You could make sqlite to return the full command information by changing [this](https://github.com/sqlectron/sqlectron-core/commit/770b06c605e66dcef86fc4c6aed2f6e12a8ca408#diff-4ae4498f315e85699c83f0479bca8e18R244)
```js
command: statement.type || (isSelect && 'SELECT'),
```
to this
```js
command: statement || (isSelect && 'SELECT'),
```
I don't remember well but I guess the idea never was to provide the whole command. Because we just use `sql-query-identifier` if the db client does not provide the query type or can't handle multiple queries statements. Is not always we have the full command information. So I don't suggest making that change.

Although you can still resolve the executionType through [EXECUTION_TYPES](https://github.com/maxcnunes/sql-query-identifier/blob/f45d4f86feaeb9ce020e9dd088e201b1e8a2407e/src/parser.js#L10). That is not exported but you should be able to access that by
```js
const { EXECUTION_TYPES } from 'sql-query-identifier/lib/parser';
const executionType = EXECUTION_TYPES[query.command];
```

**Comment by kwent** [comment]
Thank you for your answer. I ended up using `EXECUTION_TYPES` as your suggested. Thanks
